### ISSUE TITLE
Allow unittest-version to be set to "latest" or blank

### ISSUE THREAD

**Issue by camalot** [d3adb5/helm-unittest-action#15]
Currently in order to install the `latest` version you have to have `inputs.unittest-version` set to `""`. 

We have a use case, from when this property was introduced due to a bug in a version of `helm-unittest` where we have a github action variable set with a specific version. we want to now move to "latest" and continue with the latest when it is updated. 

In github variables, you cannot set it to `""`. We would need to update many repositories in order to stop them from using this github organization variable. If the action allowed either `""`, or the string `latest` it would allow us to keep the variable used, and be able to easily pin if we run in to a situation again that requires a specific version.

**Comment by d3adb5** [comment]
Fixed in #16.
