### ISSUE TITLE
v1 suddenly failing to run

### ISSUE THREAD

**Issue by jcogilvie** [d3adb5/helm-unittest-action#8]
We haven't updated our tests to run on 0.3.1 yet (and there are a couple of bugs in it).  I expect you meant to cut `v2` to work on the new version, but as of today the change seems to have applied to `v1` as well, which means `v1` is currently broken.  Can you find a way to pin `v1` to the previous version of `helm-unittest` (which worked)?

**Comment by d3adb5** [comment]
Thank you for letting me know, @jcogilvie! I changed the URL from `quintush/helm-unittest` to `helm-unittest/helm-unittest` and am passing `--version v0.2.11` to the plugin install command. I updated the `v1` tag to point to the branch where I added those changes. Can you let me know if it works for you?

**Comment by d3adb5** [comment]
As of #14, there is a `unittest-version` input to select a specific version of the `helm-unittest` plugin. It might not work with older versions of the plugin, as they might require `-3` to run properly. Either way, I'll consider this issue resolved as per the existence of v1 and as of v2.3.
