### ISSUE TITLE
Plugin Already Exists: Failing Action

### ISSUE THREAD

**Issue by rhyswilliamsza** [d3adb5/helm-unittest-action#9]
Hello 👋🏻

Thank you for this! One small thing that has come up during repeated runs on a self-hosted runner:

```
Run d3adb5/helm-unittest-action@v2
Run installScript=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
Run helm plugin install https://github.com/helm-unittest/helm-unittest >/dev/null 2>/dev/null
  helm plugin install https://github.com/helm-unittest/helm-unittest >/dev/null 2>/dev/null
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error: Process completed with exit code 1.
```

It appears that the unittest action fails to run due to the below error. Would it be possible to silently ignore if its already installed?

```
helm plugin install https://github.com/helm-unittest/helm-unittest >/dev/null 2>/dev/null
Error: plugin already exists
```

**Comment by d3adb5** [comment]
I wonder whether it's prudent to skip the installation step even if the plugin is already installed: `helm plugin ls` only really tells us the name of the plugin, its version and its description, which isn't enough to determine the right plugin is installed.

Anyway, I added an `install-mode` input in v2.1 (v2 has been updated to point to it). If you use `install-mode: if-not-present`, the action should skip installation on your self-hosted runner from now on. I'm marking this issue as resolved, but feel free to reopen if it doesn't work for you, @rhyswilliamsza.

Thank you for bringing this to my attention! :)

**Comment by rhyswilliamsza** [comment]
Thanks @d3adb5!
